# Generated by Django 4.2.7 on 2025-06-15 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'ლოდინის რეჟიმი'), ('approved', 'დადასტურებულია'), ('rejected', 'უარყოფილია'), ('completed', 'დასრულებულია'), ('cancelled', 'უარყოფილია')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, help_text='მომთხოვნის შეტყობინება')),
                ('owner_response', models.TextField(blank=True, help_text='მფლობელის პასუხი')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='books.book')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('book', 'requester')},
            },
        ),
        migrations.CreateModel(
            name='BookTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_date', models.DateTimeField()),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('actual_return_date', models.DateTimeField(blank=True, null=True)),
                ('owner_rating', models.IntegerField(blank=True, help_text='რეიტინგი 1-დან 5-მდე', null=True)),
                ('requester_rating', models.IntegerField(blank=True, help_text='რეიტინგი 1-დან 5-მდე', null=True)),
                ('owner_comment', models.TextField(blank=True)),
                ('requester_comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='requests.bookrequest')),
            ],
        ),
    ]
