# Generated by Django 4.2.7 on 2025-06-15 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('excellent', 'საუკეთესო'), ('good', 'კარგი'), ('fair', 'დამაკმაყოფილებელი'), ('poor', 'დაზიანებული')], max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('isbn', models.CharField(blank=True, max_length=13)),
                ('publication_year', models.IntegerField()),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('language', models.CharField(default='Русский', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='books/covers/')),
                ('is_available', models.BooleanField(default=True)),
                ('pickup_location', models.CharField(max_length=300)),
                ('pickup_instructions', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authors', models.ManyToManyField(related_name='books', to='authors.author')),
                ('condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookcondition')),
                ('genres', models.ManyToManyField(related_name='books', to='books.genre')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_books', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
